# Generated by Django 4.1.3 on 2022-11-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_code', models.IntegerField()),
                ('book_name', models.CharField(max_length=200)),
                ('copies_number', models.PositiveSmallIntegerField()),
                ('book_describtion', models.TextField()),
                ('book_price', models.FloatField()),
                ('book_availability', models.BooleanField()),
            ],
        ),
    ]
